#define MANIFEST                24
#define IDD_DLG_ZRJ             1000
#define IDC_STC_USR             1001
#define IDC_STC_PAS             1002
#define IDC_EDT_USR             1003
#define IDC_EDT_PAS             1004
#define IDC_CHK_AUTO_CON        1005
#define IDC_CHK_AUTO_MIN        1006
#define IDC_BTN_CONN            1007
#define IDC_BTN_EXIT            1008
#define IDC_CBO_LIST            1009
#define IDC_EDT_INFO            1010
#define IDI_ICON_RJ             1986
#define IDR_VERSION1            1
#define IDR_XPMANIFEST1         1
